### ISSUE TITLE
Need help to run the game

### ISSUE THREAD

**Issue by aswin-aach** [smileyy/scalangband#232]
Hi, 

I would like to play the game. Could you tell me how to run it from source?
I tried ` sbt run`, but it says main class isn't found. Intellij doesn't recognise Scalangband as a main class either in run configurations.

Thanks

**Comment by smileyy** [comment]
There's something wrong with the configuration in `build.sbt`, I think. It should be recognizing `main/java` and `main/scala` as source roots, but it doesn't. If you set those as source roots manually in IntelliJ it will be able to run the main `Scalangband` class, but the next time you refresh from sbt (e.g., adding a new dependency) that setting is clobbered. If anyone can figure out what's wrong with sbt before I can figure it out, I'd appreciate it!

**Comment by smileyy** [comment]
Oh, I think the issue is that sbt wants the source files under `src/main/scala`, and not directly under `main` like it is right now.  Not sure why IntelliJ set the project up like it did when I started from scratch. Let me see if moving all the source files helps.
